framework:
    http_method_override: false
    trusted_proxies: ~
    trusted_hosts: ~
    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native 